AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template to create Admin and User1 accounts with specified roles and policies."

Parameters: 

  UsersPassword:
    Description: Enter users Paaswords Here
    Type: String

  2ndAcountNumber:
    Description: Enter the number of the account gets access to the s3 bucket
    Type: String

  s3BucketName:
    Description: Enter s3 bucket name
    Type: String

Resources:

  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: s3-departments 
  
  S3BucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref S3Bucket
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Action:
            - 's3:GetObject'
            - 's3:ListObject'
          Effect: Allow
          Resource: !Join
             - !Sub arn:aws:s3:::${S3Bucket}
             - !Sub arn:aws:s3:::${S3Bucket}/IT/*
          Principal:  
            AWS: "arn:aws:iam::${2ndAcountNumber}:user/Admin-B-02"

  User1:
    Type: AWS::IAM::User
    Properties:
      UserName: IT-A-01
      LoginProfile:
        Password: !Ref UsersPassword
        PasswordResetRequired: false
      Policies:
        - PolicyName: bucket-it-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource:
                - !Sub arn:aws:s3:::${S3Bucket}
                - !Sub arn:aws:s3:::${S3Bucket}/IT/*
      
  User2:
    Type: AWS::IAM::User
    Properties:
      UserName: DevOps-A-01
      LoginProfile:
        Password: !Ref UsersPassword
        PasswordResetRequired: false
      Policies:
      - PolicyName: bucket-devops-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            Resource:
              - !Sub arn:aws:s3:::${S3Bucket}
              - !Sub arn:aws:s3:::${S3Bucket}/DevOps/*
      
  User3:
    Type: AWS::IAM::User
    Properties:
      UserName: Admin-A-01
      LoginProfile:
        Password: !Ref UsersPassword
        PasswordResetRequired: false
      Policies:
      - PolicyName: bucket-admin-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            Resource:
              - !Sub arn:aws:s3:::${S3Bucket}
              - !Sub arn:aws:s3:::${S3Bucket}/*
      

  User4:
    Type: AWS::IAM::User
    Properties:
      UserName: Marketing-A-01
      LoginProfile:
        Password: !Ref UsersPassword
        PasswordResetRequired: false
      Policies:
        - PolicyName: bucket-marketing-access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - s3:*
              Resource:
                - !Sub arn:aws:s3:::${S3Bucket}
                - !Sub arn:aws:s3:::${S3Bucket}/Marketing/*

   

        
